"""add progress to training_runs

Revision ID: 39404bac27c5
Revises: 70f97ee7b318
Create Date: 2026-04-22 21:15:34.708902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39404bac27c5'
down_revision: Union[str, Sequence[str], None] = '70f97ee7b318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column with temporary default so existing rows don’t break
    op.add_column(
        'training_runs',
        sa.Column('progress', sa.Integer(), nullable=False, server_default='0')
    )

    # Remove the default (optional, since we already handle default in model)
    op.alter_column('training_runs', 'progress', server_default=None)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_runs', 'progress')
    # ### end Alembic commands ###
