"""add model_path to training_runs

Revision ID: 69e9a0e32ee4
Revises: a52fe8ca8c61
Create Date: 2026-04-25 21:51:55.668414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e9a0e32ee4'
down_revision: Union[str, Sequence[str], None] = 'a52fe8ca8c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_runs', sa.Column('model_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_runs', 'model_path')
    # ### end Alembic commands ###
